### PR TITLE
#fragment_name_with_digest optional dependencies parameter

### PR DESCRIPTION
**Pull request by s12chung**
Fixes conflict with `jbuilder` and possibly other gems from: https://github.com/rails/cache_digests/commit/7ce6e7ee61740bb1c07914efc002871fcb93dc7a#L2R3

### CODE REVIEW

**Comment by gokure** [comment]
+1
the second argument will break `jbuilder` gem now

**Comment by john-999** [comment]
+1
v0.3.0 throws "wrong number of arguments (1 for 2)" argument error, when used with gem https://github.com/n8/multi_fetch_fragments

**Comment by drale2k** [comment]
+1 it will break jbuilder for me

This fork fixes the issue, maybe it can be merged? https://github.com/s12chung/cache_digests

**Comment by s12chung** [comment]
it's been about a month. it's a pretty simple change. anything I need to do to get it merged?

**Comment by dhh** [comment]
Can you make this update to rails/master as well? I think we need to get it into 4-0-0 and 4-0-stable as well.

**Comment by s12chung** [comment]
Doesn't seem like it's needed... Unless you want the `dependencies` parameter to be exposed publicly for: https://github.com/rails/rails/blob/master/actionpack/lib/action_view/helpers/cache_helper.rb#L154

**Comment by dhh** [comment]
Ah, wasn't aware of the fork there.

**Pull request merged**
