### PR TITLE
Allow registering custom dependency trackers

### PR DESCRIPTION
**Pull request by dasch**
This refactoring would allow various template handlers, including very non-Erb ones such as Mustache, to register custom dependency trackers.

I'd like to support this syntax for Mustache-like and Liquid-like templates:

``` ruby
class SomeMustache < Mustache
  def self.dependencies
    %w[ foo/bar baz/bum ]
  end
end

class MustacheDependencyTracker
  def self.call(name, template)
    mustache_class = get_that_class_somehow
    mustache_class.dependencies
  end
end

CacheDigests::DependencyTracker.register_tracker(:mustache, MustacheDependecyTracker)
```

(I'm not using Mustache, but something a bit like it).

I'm not sure exactly how much support there currently is for non-Erb template types. If some types are already supported, perhaps a base class can be extracted and each concrete tracker can subclass from it, so that there would be an ErbTracker, BuilderTracker, etc.

I'm not sure I got the `Template#handler` syntax right, though -- will the handler by a symbol, or the actual handler class? The Rails docs weren't very clear on that.

### CODE REVIEW

**Comment by dasch** [comment]
Also: this refactoring would make it easier to test the specific dependency tracking code, e.g. by passing in the source directly instead of using file fixtures.

``` ruby
class ErbTrackerTest < TestCase
  def test_extracts_explicit_dependencies
    source = %(<%# Template Dependency: foo/bar %>)
    template = FakeTemplate.new("baz", source)
    assert_equal ["foo/bar"], ErbTracker.call("baz", template)
  end
end
```

**Comment by dasch** [comment]
@dhh this has been tested and works with [Curly](https://github.com/dasch/curly). However, I'm not quite sure how tracker registry should work. Since `Template#handler` returns the actual handler object, not a symbolic representation (e.g. `:erb`) we need to do e.g.

``` ruby
CacheDigests::DependencyTracker.register_tracker(ERB, ErbTracker)
```

I'm not sure if it's possible to get a symbolic representation of the template type, since it doesn't seem to be stored on Template. Would it be okay to use the actual objects as keys?

**Update:** We _could_ use `ActionView::Template.handler_for_extension` to resolve the symbolic representation at startup time. That's probably the best.

**Comment by dhh** [comment]
Hmm, how do we currently lookup template handler from the extension? There must be something similar to do here.

**Comment by dasch** [comment]
> Hmm, how do we currently lookup template handler from the extension?

The template resolvers call `ActionView::Template.handler_for_extension` with the symbolic name, getting a handler back. Unfortunately, the symbolic name is not stored on the Template instances the same way `formats` is, so we only have the handler object to go by.

I think it would be best if `register_tracker` did something like this:

``` ruby
def register_tracker(extension, tracker)
  handler = ActionView::Template.handler_for_extension(extension)
  @trackers[handler] = tracker
end
```

**Comment by dasch** [comment]
@ddh I think this is looking pretty good. The only remaining question I have is whether to register the ERBTracker with other supported extensions, e.g. builder or HAML?

**Comment by dhh** [comment]
Looking good. Can you cross-post a pull to rails/master? Then we'll get a review going.

**Comment by dasch** [comment]
@dhh there was already one open. I've rebased it and updated it with the changes from this PR: https://github.com/rails/rails/pull/8530

**Pull request merged**
