### PR TITLE
Added a note about required restart

### PR DESCRIPTION
**Pull request by genezys**
A restart is required whenever the template changes. 
As I don't think there is another solution,
it should be documented

### CODE REVIEW

**Comment by fgrehm** [comment]
I was able to get it working under development with this monkey patch:

``` terminal
if Rails.env.development?
  class CacheDigests::TemplateDigestor
    cattr_accessor(:cache) { ActiveSupport::Cache::NullStore.new }
  end
end
```

Just place this code on a initializer file and things will work just fine ;-)
This might also be a fix / workaround for #8 

@ddh does it make sense to have something like this code on the gem itself?

**Comment by genezys** [comment]
Thanks @fgrehm for the idea. I ended adding the following line at the end of my environments/development.rb

```
CacheDigests::TemplateDigestor.cache = ActiveSupport::Cache::NullStore.new
```

**Comment by dhh** [comment]
If you don't want the templates cached, why would you turn caching on in development mode? By default it's off. I don't really understand this request?

**Comment by fgrehm** [comment]
@genezys that's actually better that what I've done :-)

@dhh not sure if I got it right but looking at [this part of the code](https://github.com/rails/cache_digests/blob/master/lib/cache_digests/template_digestor.rb#L30-L34) seems that this specific cache from the code I provided is used to avoid "recalculating" the template digest for a given fragment (which under development might change).
Even though we are replacing it with a `NullStore`, the result of rendering the template would still be cached if the application cache is enabled.

**Comment by dhh** [comment]
Fabio, if you leave caching off in development, then the template digest is not used. If you turn caching ON, then template digests are used, and so are the caches. Isn't that the point? Otherwise you're paying for the stat calls on every request to check the whole graph, which might take a while, somewhat defeating the purpose of turning caching on.

**Comment by fgrehm** [comment]
Maybe I'm missing something but because of the `ActiveSupport::Cache::MemoryStore` set [here](https://github.com/rails/cache_digests/blob/master/lib/cache_digests/template_digestor.rb#L25), digests won't change if the views have changed, that's why we have to restart the app to see the changes :-)

I know that each request would end up recalculating the digest, but we'd still be caching the result of whatever hard work is being done on the fragment itself. On environments other than development we'd still keep the `MemoryStore` around.

**Comment by dhh** [comment]
Correct, but the whole cache do/end call is being ignored when caching is off-by-default in development. You are only seeing this problem as you turn caching on explicitly, no?

**Comment by fgrehm** [comment]
Yup I forgot to mention that, my bad :-P
Maybe the README note that @genezys proposed could be changed to something like:

```
Note that if your application cache is enabled, the template digest will not be recomputed until you restart your application and you will have to restart the app whenever you change template code.

For development environment you might want to cache your fragments AND have dependent partials changes detected (with the penalty of recomputing the digests for each request). For that you can add `CacheDigests::TemplateDigestor.cache = ActiveSupport::Cache::NullStore.new` to your development configuration.
```

WDYT?

**Comment by dhh** [comment]
:+1:

**Comment by genezys** [comment]
I agree the new comment is better. I will create a new request with it.

@dhh About enabling caching in development, I think this is a good idea to check the behavior of caching in development because caching has an impact on the logic of the app. I want to see if my queries are ok, if I missed a partial declaration or if I missed a touch attribute on a relation. When I enable caching in development, I don't need the performance improvement, I just need the caching behavior.

**Comment by fgrehm** [comment]
@genezys I had some free time today and ended up creating the new request :-)

**Pull request closed without merging**
