### PR TITLE
Format the regex with code delimiters

### PR DESCRIPTION
**Pull request by dasch**
Makes the regex more readable.

### CODE REVIEW

**Comment by dhh** [comment]
Please rebase.

**Comment by dasch** [comment]
@dhh done.

What do you feel about #19?

**Comment by dhh** [comment]
I like the idea. Have you actually used this for a second dependency tracker, like for mustache or something else?

**Comment by dasch** [comment]
@dhh I developed it for [Curly](https://github.com/dasch/curly), which is similar to Mustache in design. I haven't had it running for a while, I can try hooking it up again tomorrow. There's also an open PR on the Rails repo, but it hasn't received much attention.

**Comment by dhh** [comment]
I'd definitely be happy to support this extension. Makes good sense to me.

**Pull request merged**
